#*************************************************
#****************datasets args********************
#*************************************************
filepaths:
  checkpoint: checkpoints/img2score_epoch5-piano-2024-05-14_20-15-59.pth

  lifttokenizer: drumtokenizers/drumtokenizer_lift.json
  pitchtokenizer: drumtokenizers/drumtokenizer_pitch.json
  rhythmtokenizer: drumtokenizers/drumtokenizer_rhythm.json
  notetokenizer: drumtokenizers/drumtokenizer_note.json

channels: 1
patch_size: 16
max_height: 128
max_width: 1280
max_seq_len: 128

pad_token: 0
bos_token: 1
eos_token: 2
nonote_token: 0

num_rhythmtoken: 262
noteindexes:
- 129
- 130
- 131
- 132
- 133
- 134
- 135
- 136
- 137
- 138
- 139
- 140
- 141
- 142
- 143
- 144
- 145
- 146
#*************************************************
#****************encoder args***************
#*************************************************
encoder_structure: hybrid
encoder_depth: 4
backbone_layers:
- 2
- 3
- 7
encoder_dim: 256
encoder_heads: 8
#*************************************************
#****************decoder args***************
#*************************************************
num_note_tokens: 3
num_rhythm_tokens: 262 
num_pitch_tokens: 72
num_lift_tokens: 8
decoder_dim: 256
decoder_depth: 4
decoder_heads: 8
decoder_args:
  attn_on_attn: true
  cross_attend: true
  ff_glu: true
  rel_pos_bias: false
  use_scalenorm: false