spring:
  datasource:
    url: jdbc:mysql://localhost:3306/let_me_drum
    # url: jdbc:mysql://db:3306/let_me_drum
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
springdoc:
  swagger-ui:
    groups-order: desc
    operations-sorter: method
env:
  jwt:
    secret-key: 'LetMeDrum20250125LetMeDrum20250125LetMeDrum20250125LetMeDrum20250125'
    access-token-exp: 1000000
    refresh-token-exp: 1000000
