x-common-variables: &common-variables
  CLIENT_GATEWAY_SERVICE_URL: http://gateway-service:28080
  SPRING_DATASOURCE_URL: your-datasource-url
  SPRING_DATASOURCE_USERNAME: your-user-name
  SPRING_DATASOURCE_PASSWORD: your-password
  SPRING_DATA_REDIS_HOST: your-redis-host
  SPRING_DATA_REDIS_PORT: 26379
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: your-eureka-url
  GATEWAY_SERVICE_URL: your-gateway-url
  SERVER_MAX_HTTP_REQUEST_HEADER_SIZE: 10MB

services:
  gateway-service:
    image: louie8821/gateway-service:test-latest
    container_name: gateway-service
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "28080:8080"
    environment:
      <<: *common-variables
    depends_on:
      discovery-service:
        condition: service_healthy
  discovery-service:
    image: louie8821/discovery-service:test-latest
    container_name: discovery-service
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "28761:8761"
    healthcheck:
      test: ["CMD", "curl", "http://discovery-service:8761/actuator/health"]
      interval: 10s
      retries: 20
      timeout: 5s
      start_period: 10s
  db:
    image: mysql:8.0
    container_name: database_letmedrum
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: let_me_drum
      MYSQL_ROOT_PASSWORD: your-password
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host", "db"]
      interval: 10s
      retries: 20
      timeout: 5s
      start_period: 10s
  redis:
    image: redis:6.2.6-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "26379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/config:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 20
      timeout: 5s
      start_period: 10s
