on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, user-service, verification-service, gateway-service, music-service, discovery-service]

    steps:
      # - uses: actions/checkout@v3

      # - name: Set Up Java 17
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: 17
      #     distribution: "temurin"

      # - name: gradle build caching
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.gradle/caches
      #       ~/.gradle/wrapper
      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gradle-

      # - name: gradle setup
      #   uses: gradle/gradle-build-action@v2

      - name: checkout repo with submodule
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true

      # - name: Build :${{ matrix.service }}
      #   run: |
      #     chmod +x ./gradlew
      #     ./gradlew :${{ matrix.service }}:build

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
