on:
  push:
    branches:
      - master
      - backend/master
  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # service: [music-service]
        service: [auth-service, user-service, verification-service, gateway-service, music-service, discovery-service]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: set config file key # xx-service -> XX_SERVICE_CONFIG
        run: |
          SERVICE_NAME=$(echo ${{ matrix.service }} | tr '-' '_' | tr '[:lower:]' '[:upper:]')
          echo "SERVICE_SECRET=${SERVICE_NAME}_CONFIG" >> $GITHUB_ENV

      - name: copy config files
        run: |
          mkdir -p backend/config-backend/dev backend/config-backend/dev/${{ matrix.service }}
          echo "${{ secrets[env.SERVICE_SECRET] }}" | base64 --decode > backend/config-backend/dev/${{ matrix.service }}/application.yml
          echo "${{ secrets.COMMON_YML }}" | base64 --decode > backend/config-backend/dev/common.yml

      - name: Set version tag
        run: echo "VERSION_TAG=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: backend/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:test-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
